/*
 * Designed and developed by 2026 skydoves (Jaewoong Eum)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.skydoves.crayfish.device

import android.graphics.Bitmap
import android.graphics.Canvas
import com.github.skydoves.crayfish.decode.CropSource
import com.github.skydoves.crayfish.decode.DecodeBudget
import com.github.skydoves.crayfish.decode.ImageRegion
import com.github.skydoves.crayfish.decode.ImageSize
import com.github.skydoves.crayfish.decode.SampleSize
import com.github.skydoves.crayfish.decode.createRegionDecoder
import com.github.skydoves.crayfish.encode.EncodeOptions
import com.github.skydoves.crayfish.encode.EncodedFormat
import com.github.skydoves.crayfish.encode.encodeImage
import kotlinx.coroutines.runBlocking
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * The claims that are only true on a real device.
 *
 * Android is where the limits this library is designed around actually live: a hardware-accelerated
 * canvas that refuses a bitmap past roughly 100MB, a GPU texture cap that is still 4096 on the
 * largest share of shipping hardware, and a per-app heap a phone will kill you for exceeding. None
 * of that exists on the JVM, so every desktop measurement so far has been an argument by analogy.
 */
class DeviceCropTest {

  /**
   * Fixtures live on the device rather than inside the APK.
   *
   * A 108MP JPEG is only 1.8MB encoded, so shipping it would be affordable, but Compose's resource
   * plugin does not configure an assets copy for a device-test source set, and more importantly the
   * fixture is generated by a Gradle task that already knows how to make it. `pushDeviceFixtures`
   * puts it here; `/data/local/tmp` is world-readable, which is why instrumentation fixtures live
   * there rather than in app storage that the test process may not own.
   */
  private fun asset(name: String): File {
    val file = File(FIXTURE_DIR, name)
    check(file.isFile && file.length() > 0) {
      "missing device fixture $file: run ./gradlew :crayfish:pushDeviceFixtures"
    }
    return file
  }

  @Test
  fun cropsA108MegapixelPhotoOnDevice() = runBlocking {
    val decoder = assertNotNull(
      createRegionDecoder(CropSource.FilePath(asset(SENSOR_108MP).absolutePath)),
      "the device could not open the fixture",
    )
    decoder.use {
      assertEquals(ImageSize(12_000, 9_000), it.imageSize)

      val region = ImageRegion(3_000, 2_000, 9_000, 8_000)
      val sampleSize = SampleSize.forDecode(region.size, VIEWPORT, DecodeBudget.ForDisplay)
      val decoded = assertNotNull(it.decodeRegion(region, sampleSize))

      decoded.use { result ->
        val bytes = result.width.toLong() * result.height.toLong() * 4L
        assertTrue(
          bytes <= DecodeBudget.ForDisplay.maxByteCount,
          "the device produced ${result.width}x${result.height} = $bytes bytes",
        )
      }
    }
  }

  /**
   * The failure this library exists to prevent, checked against the API that produces it.
   *
   * `Canvas.throwIfCannotDraw` is what raises `Canvas: trying to draw too large bitmap`, and the
   * threshold is a device property rather than a constant, which is exactly why asking the device
   * is worth more than hard-coding 100MB.
   */
  @Test
  fun everyDecodedRegionIsSomethingThisDeviceWillActuallyDraw() = runBlocking {
    val decoder = assertNotNull(
      createRegionDecoder(CropSource.FilePath(asset(SENSOR_108MP).absolutePath)),
    )
    decoder.use {
      val region = ImageRegion.of(it.imageSize)
      val sampleSize = SampleSize.forDecode(region.size, VIEWPORT, DecodeBudget.ForDisplay)
      val decoded = assertNotNull(it.decodeRegion(region, sampleSize))

      decoded.use { result ->
        val bitmap = result.image.bitmap
        // The limits are a property of the device, not of the bitmap being asked about, and a
        // Canvas cannot be built over an immutable one, which every decoded bitmap here is. A 1x1
        // scratch bitmap asks the same question without copying 100MB to do it.
        val scratch = Bitmap.createBitmap(1, 1, Bitmap.Config.ARGB_8888)
        val probe = Canvas(scratch)
        try {
          assertTrue(
            bitmap.width <= probe.maximumBitmapWidth,
            "width ${bitmap.width} exceeds this device's maximum bitmap width " +
              "(${probe.maximumBitmapWidth})",
          )
          assertTrue(
            bitmap.height <= probe.maximumBitmapHeight,
            "height ${bitmap.height} exceeds this device's maximum bitmap height " +
              "(${probe.maximumBitmapHeight})",
          )
        } finally {
          scratch.recycle()
        }
        // The real proof: hand it to a hardware-backed canvas and let the platform object if it
        // wants to. A bitmap past the limit throws here rather than returning anything.
        android.graphics.Picture().run {
          val canvas = beginRecording(bitmap.width, bitmap.height)
          canvas.drawBitmap(bitmap, 0f, 0f, null)
          endRecording()
        }
      }
    }
  }

  @Test
  fun cropsAndEncodesOnDeviceWithinTheOutputBudget() = runBlocking {
    val decoder = assertNotNull(
      createRegionDecoder(CropSource.FilePath(asset(SENSOR_108MP).absolutePath)),
    )
    decoder.use {
      val region = ImageRegion(0, 0, 8_000, 8_000)
      val sampleSize = SampleSize.forDecode(region.size, region.size, DecodeBudget.ForOutput)
      val decoded = assertNotNull(it.decodeRegion(region, sampleSize))

      decoded.use { result ->
        val bytes = assertNotNull(
          encodeImage(result.image, EncodeOptions(EncodedFormat.JPEG, lossyQuality = 90)),
        )
        assertTrue(bytes.size > 1024, "a JPEG of a real crop should not be ${bytes.size} bytes")
        assertEquals(0xFF.toByte(), bytes[0])
        assertEquals(0xD8.toByte(), bytes[1])
      }
    }
  }

  /**
   * The Android decoder must not hand back a hardware bitmap.
   *
   * Its pixels cannot be read, so the encode path and the Exif reorientation both fail on one, and
   * `ALLOCATOR_DEFAULT` hands one out on API 28 and up unless a decoder asks otherwise.
   */
  @Test
  fun theDecodedPixelsAreReadable() = runBlocking {
    val decoder =
      assertNotNull(createRegionDecoder(CropSource.FilePath(asset(UHD_PNG).absolutePath)))
    decoder.use {
      val decoded = assertNotNull(it.decodeRegion(ImageRegion(0, 0, 256, 256), sampleSize = 1))
      decoded.use { result ->
        val pixels = assertNotNull(
          result.image.readArgbPixels(),
          "a hardware bitmap reached the caller; the encode path cannot read one",
        )
        assertEquals(256 * 256, pixels.size)
      }
    }
  }

  private companion object {
    const val SENSOR_108MP = "sensor-108mp.jpg"
    const val UHD_PNG = "uhd.png"
    val VIEWPORT = ImageSize(1_080, 2_340)
    const val FIXTURE_DIR = "/data/local/tmp/crayfish-fixtures"
  }
}
