/*
 * Designed and developed by 2026 skydoves (Jaewoong Eum)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.skydoves.crayfish.decode

/**
 * A byte sink for fixtures that no encoder would ever produce.
 *
 * [ImageHeaders] builds files that are correct; this builds files that are wrong in one named way
 * each, which is the half of the input space a hand-rolled parser is actually judged on. Every
 * field is written out longhand so the shape under test is legible in the test source rather than
 * buried in a library call: a fixture generated by an encoder only ever proves that the parser
 * agrees with that encoder.
 */
internal class ByteWriter {
  private val out = mutableListOf<Byte>()

  fun bytes(vararg values: Int) {
    values.forEach { out += it.toByte() }
  }

  fun raw(values: ByteArray) {
    values.forEach { out += it }
  }

  fun ascii(text: String) {
    text.forEach { out += it.code.toByte() }
  }

  fun beU16(value: Int) = bytes(value ushr 8, value)

  fun beU32(value: Int) = bytes(value ushr 24, value ushr 16, value ushr 8, value)

  fun beU64(value: Long) {
    for (shift in 56 downTo 0 step 8) out += (value ushr shift).toByte()
  }

  fun leU16(value: Int) = bytes(value, value ushr 8)

  fun leU24(value: Int) = bytes(value, value ushr 8, value ushr 16)

  fun leU32(value: Int) = bytes(value, value ushr 8, value ushr 16, value ushr 24)

  fun build(): ByteArray = out.toByteArray()
}

internal fun writeBytes(block: ByteWriter.() -> Unit): ByteArray = ByteWriter().apply(block).build()

// -------------------------------------------------------------------------------------------------
// JPEG - ITU-T T.81 marker segments.
// -------------------------------------------------------------------------------------------------

/** A JPEG: the start-of-image marker, then exactly the bytes [body] writes. */
internal fun jpegOf(body: ByteWriter.() -> Unit): ByteArray = writeBytes {
  bytes(0xFF, 0xD8)
  body()
}

/**
 * One marker segment.
 *
 * @param declaredLength what the two-byte length field says. For a well-formed segment that is the
 *   payload's length plus the two bytes of the field itself; these fixtures exist to write anything
 *   else.
 */
internal fun ByteWriter.segment(
  marker: Int,
  payload: ByteArray = ByteArray(0),
  declaredLength: Int = payload.size + 2,
) {
  bytes(0xFF, marker)
  beU16(declaredLength)
  raw(payload)
}

/** A baseline start-of-frame payload: precision, height, width, then one component. */
internal fun sofPayload(width: Int, height: Int): ByteArray = writeBytes {
  bytes(0x08)
  beU16(height)
  beU16(width)
  bytes(0x01) // one component
  bytes(0x01, 0x11, 0x00)
}

/** An `APP0`/JFIF payload, the segment a camera writes first and the walk has to step over. */
internal fun jfifPayload(): ByteArray = writeBytes {
  ascii("JFIF")
  bytes(0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00)
}

/** Start of scan, its payload, and enough entropy-coded bytes for the walk to run into. */
internal fun ByteWriter.startOfScan() {
  segment(0xDA, writeBytes { bytes(0x01, 0x01, 0x00, 0x00, 0x3F, 0x00) })
  bytes(0x12, 0x34, 0x56, 0x78)
  bytes(0xFF, 0xD9)
}

// -------------------------------------------------------------------------------------------------
// PNG, GIF and RIFF/WebP.
// -------------------------------------------------------------------------------------------------

/** A PNG: the eight-byte signature, then exactly the bytes [body] writes. */
internal fun pngOf(body: ByteWriter.() -> Unit): ByteArray = writeBytes {
  bytes(0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A)
  body()
}

/** A PNG `IHDR` chunk: length, type, the two dimensions, then the five trailing fields. */
internal fun ByteWriter.ihdr(width: Int, height: Int) {
  beU32(13)
  ascii("IHDR")
  beU32(width)
  beU32(height)
  bytes(0x08, 0x06, 0x00, 0x00, 0x00)
  beU32(0) // CRC, which nothing here reads
}

/**
 * A RIFF/WebP file.
 *
 * @param declaredRiffSize the size the RIFF header claims, which for these fixtures is free to
 *   disagree with how many bytes actually follow it.
 */
internal fun webPOf(declaredRiffSize: Int? = null, body: ByteWriter.() -> Unit): ByteArray {
  val chunks = writeBytes(body)
  return writeBytes {
    ascii("RIFF")
    leU32(declaredRiffSize ?: (4 + chunks.size))
    ascii("WEBP")
    raw(chunks)
  }
}

/** A RIFF chunk: fourcc, a little-endian size, the payload, and the pad byte to an even length. */
internal fun ByteWriter.chunk(
  fourCc: String,
  payload: ByteArray,
  declaredSize: Int = payload.size,
) {
  ascii(fourCc)
  leU32(declaredSize)
  raw(payload)
  if (payload.size % 2 == 1) bytes(0x00)
}

/** A simple-lossy `VP8 ` payload: the frame tag, the sync code, then the two 14-bit dimensions. */
internal fun vp8Payload(width: Int, height: Int): ByteArray = writeBytes {
  bytes(0x00, 0x00, 0x00) // frame tag
  bytes(0x9D, 0x01, 0x2A) // sync code
  leU16(width)
  leU16(height)
}
